export const defaultStoreConfig = {
  id: "singleton",
  storeName: "Nome da Loja",
  storeSlug: "loja-template",
  domain: "https://sualoja.com.br",
  instagramUrl: "",
  city: "Sua cidade",
  state: "UF",
  logoUrl: "",
  faviconUrl: "/favicon.ico",
  primaryColor: "#f7d117",
  topBannerText: "Entrega local e atendimento pelo WhatsApp",
  isBannerVisible: true,
  whatsappNumber: "5500000000000",
  heroImage1: "/post01.jpg",
  heroImage2: "/post01.jpg",
  heroImage3: "/post01.jpg",
  seoTitle: "Nome da Loja | Loja Online",
  seoDescription: "Loja online com pedido no site e fechamento pelo WhatsApp.",
  heroEyebrow: "Loja Online",
  heroTitle: "Escolha seu produto",
  heroHighlight: "e compre com atendimento",
  heroDescription: "Veja os produtos, selecione o que precisa e finalize o atendimento pelo WhatsApp.",
  footerDescription: "Loja online com vitrine organizada, pedido pelo site e fechamento direto no WhatsApp.",
  privacyText:
    "Os dados informados no pedido ficam restritos ao atendimento da loja e nao sao vendidos a terceiros.",
  termsText:
    "Pedidos feitos pelo site sao confirmados pelo WhatsApp. Disponibilidade, pagamento, retirada e entrega sao alinhados durante o atendimento.",
};
