ALTER TABLE "SiteConfig" ADD COLUMN "storeName" TEXT NOT NULL DEFAULT 'Nome da Loja';
ALTER TABLE "SiteConfig" ADD COLUMN "storeSlug" TEXT NOT NULL DEFAULT 'loja-template';
ALTER TABLE "SiteConfig" ADD COLUMN "domain" TEXT NOT NULL DEFAULT 'https://sualoja.com.br';
ALTER TABLE "SiteConfig" ADD COLUMN "instagramUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteConfig" ADD COLUMN "city" TEXT NOT NULL DEFAULT 'Sua cidade';
ALTER TABLE "SiteConfig" ADD COLUMN "state" TEXT NOT NULL DEFAULT 'UF';
ALTER TABLE "SiteConfig" ADD COLUMN "logoUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteConfig" ADD COLUMN "faviconUrl" TEXT NOT NULL DEFAULT '/favicon.ico';
ALTER TABLE "SiteConfig" ADD COLUMN "primaryColor" TEXT NOT NULL DEFAULT '#f7d117';
ALTER TABLE "SiteConfig" ADD COLUMN "seoTitle" TEXT NOT NULL DEFAULT 'Nome da Loja | Loja Online';
ALTER TABLE "SiteConfig" ADD COLUMN "seoDescription" TEXT NOT NULL DEFAULT 'Loja online com pedido no site e fechamento pelo WhatsApp.';
ALTER TABLE "SiteConfig" ADD COLUMN "heroEyebrow" TEXT NOT NULL DEFAULT 'Loja Online';
ALTER TABLE "SiteConfig" ADD COLUMN "heroTitle" TEXT NOT NULL DEFAULT 'Escolha seu produto';
ALTER TABLE "SiteConfig" ADD COLUMN "heroHighlight" TEXT NOT NULL DEFAULT 'e compre com atendimento';
ALTER TABLE "SiteConfig" ADD COLUMN "heroDescription" TEXT NOT NULL DEFAULT 'Veja os produtos, selecione o que precisa e finalize o atendimento pelo WhatsApp.';
ALTER TABLE "SiteConfig" ADD COLUMN "footerDescription" TEXT NOT NULL DEFAULT 'Loja online com vitrine organizada, pedido pelo site e fechamento direto no WhatsApp.';
ALTER TABLE "SiteConfig" ADD COLUMN "privacyText" TEXT NOT NULL DEFAULT 'Os dados informados no pedido ficam restritos ao atendimento da loja e nao sao vendidos a terceiros.';
ALTER TABLE "SiteConfig" ADD COLUMN "termsText" TEXT NOT NULL DEFAULT 'Pedidos feitos pelo site sao confirmados pelo WhatsApp. Disponibilidade, pagamento, retirada e entrega sao alinhados durante o atendimento.';

ALTER TABLE "SiteConfig" ALTER COLUMN "topBannerText" SET DEFAULT 'Entrega local e atendimento pelo WhatsApp';
ALTER TABLE "SiteConfig" ALTER COLUMN "whatsappNumber" SET DEFAULT '5500000000000';
